### ISSUE TITLE
Enhance DynamicContentExtensions.SetPropertyInDataItem to handle enums

### ISSUE THREAD

**Issue by cspath1** [AndcultureCode/AndcultureCode.CSharp.Sitefinity.Conductors#6]
Via using this in a client project, we discovered that Sitefinity is handling enumerations in such a way that they need to be handled differently. Specifically, Sitefinity's ChoiceField (i.e. select dropdowns) store values as strings, meaning corresponding enum values need to be set as a string when adapting one of our models to a `DynamicContent` object.

**Comment by KevinBusch** [comment]
PR #7 Add means of handling enums
